services:
  postgres:
    image: postgres:16-alpine
    container_name: authsphere-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authsphere
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  redis:
    image: redis:8-alpine
    container_name: authsphere-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

volumes:
  postgres_data:
